### ISSUE TITLE
shared_samples.py error "vcf1 is not defined."

### ISSUE THREAD

**Issue by MPetershack** [wheaton5/souporcell#237] opened 2024-07-22 20:23 UTC
Hello,

I am attempting to use the shared_samples.py script to genotype my pseudobulk dataset with a bulk 5' Tag-based RNA seq dataset but Am running into issues. I have converted both the pseudobulk and bulk RNA-seq to VCF but could not run the command as it will not recognize my VCF files. I have tried:
1. Putting the VCFs (pseudobulk and regular bulk sets) in the same directory.
2. Putting them in different directories and pointing command to each
3. Renaming VCFs to naming system found in the documentation  (souporcell_merged_sorted_vcf.vcf.gz, & common_variants_covered.vcf)

But the code always breaks at line 24, with the traceback saying: "NameError: name 'vcf1' is not defined"

Anyone have ideas to help me out?  Thanks!

Matt

**Comment by wheaton5** [comment] 2024-07-24 01:15
After some personal communication, this seems to be out of the scope of what shared_samples.py was intended for. With some simple reformatting I got past this issue but then didn't have clusters.tsv for each sample. And one vcf was not multi-sample. Not saying this isn't possible, but it requires 2 properly formatted multi-sample vcfs and cluster.tsv files with cluster names matching the samples in the vcfs.

I will close this issue, but feel free to reopen it if you need further advice.

**Closed by wheaton5** 2024-07-24 01:15 UTC
